"""Generated by Clawforge. Pydantic handoffs for room."""
from pydantic import BaseModel
from typing import List
class ContentPackage(BaseModel):
    title: str
    insights: List[str]
    risk_score: int = 0
    to_obsidian_frontmatter: lambda self: f"---\ntitle: {self.title}\n---"
print("Handoff models forged for Obsidian integration.")