#!/usr/bin/env bash
# Tailnet Serve routes for the ReClaw Hetzner stack (Docker compose + host Tailscale).
#
# Dual-path OpenClaw gateway (PDANet USB-tether resistant):
#   PRIMARY  Android URL:  wss://openclaw.tail20a090.ts.net
#   FALLBACK (debug/LAN):  ws://100.108.130.82:18789  (bind=lan; mobile prefers wss)
#
# PDANet USB tethering hijacks phone/PC routes and breaks Tailscale. When pairing:
#   1) Disconnect PDANet USB tether (or disable "USB tethering" / PDANet share)
#   2) Keep phone on cellular (or Wi‑Fi) with Tailscale connected
#   3) Use ONLY the MagicDNS wss URL below — never a rotating public IP
#
# Serve multi-path keeps ReClaw API + MCP on the same hostname (no public Funnel).
# grok.com MCP uses Funnel (mcp_public_url.txt) (data/mcp_public_url.txt).
set -euo pipefail

MCP_PORT="${FASTMCP_PORT:-8100}"
GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
RECLAW_PORT="${RECLAW_API_PORT:-8000}"
MAGIC_DNS="${OPENCLAW_MAGIC_DNS:-openclaw.tail20a090.ts.net}"
TS_IP="$(tailscale ip -4 2>/dev/null || echo 100.108.130.82)"
URL_FILE="${OPENCLAW_ANDROID_URL_FILE:-/root/ReClaw-2.0/data/openclaw_android_url.txt}"

# Re-assert multi-path Serve (idempotent). Gateway must listen on 127.0.0.1:18789.
tailscale serve --bg --set-path=/ "http://127.0.0.1:${GATEWAY_PORT}" 2>/dev/null || true
tailscale serve --bg --set-path=/reclaw "http://127.0.0.1:${RECLAW_PORT}" 2>/dev/null || true
tailscale serve --bg --set-path=/reclaw-mcp "http://127.0.0.1:${MCP_PORT}" 2>/dev/null || true

# Stable Android SOT (phone / Control UI / agents read this)
mkdir -p "$(dirname "${URL_FILE}")"
cat > "${URL_FILE}" <<EOF
# OpenClaw Android / remote client — stable URLs (ReClaw Hetzner)
# Generated by scripts/ensure-tailscale-mcp-funnel.sh — do not hand-edit stale IPs.
#
# PRIMARY (use this on the phone):
wss://${MAGIC_DNS}
#
# Control UI (browser on tailnet):
https://${MAGIC_DNS}/
#
# Health:
https://${MAGIC_DNS}/health
http://127.0.0.1:${GATEWAY_PORT}/health
#
# FALLBACK direct tailnet TCP (bind=lan; prefer PRIMARY wss on Android):
ws://${TS_IP}:${GATEWAY_PORT}
#
# PDANet: disconnect USB tethering before pairing. Tether breaks Tailscale routes.
# Token: OPENCLAW_GATEWAY_TOKEN / gateway.auth.token in ~/.openclaw/openclaw.json
EOF

echo "[+] Tailnet Serve (phone/laptop with Tailscale on the same tailnet):"
tailscale serve status || true
echo "[+] PRIMARY Android URL:  wss://${MAGIC_DNS}"
echo "[+] Control UI:           https://${MAGIC_DNS}/"
echo "[+] FALLBACK tailnet:     ws://${TS_IP}:${GATEWAY_PORT}  (bind=lan)"
echo "[+] SOT file:             ${URL_FILE}"
echo "[+] ReClaw API health:    https://${MAGIC_DNS}/reclaw/health"
echo "[+] Tailnet MCP:          https://${MAGIC_DNS}/reclaw-mcp/mcp"
if [[ -f /root/ReClaw-2.0/data/mcp_public_url.txt ]]; then
  echo "[+] grok.com MCP: $(cat /root/ReClaw-2.0/data/mcp_public_url.txt)"
else
  echo "[!] grok.com MCP: start reclaw-mcp-tunnel.service (cloudflared)"
fi
