#!/usr/bin/env bash
# Set up a *named* Cloudflare tunnel for the ReClaw MCP public URL (stable hostname).
# Prerequisites: cloudflared installed; `cloudflared tunnel login` once (browser).
# Does NOT enable Access by itself — see docs/operator/NAMED-MCP-TUNNEL.md
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
NAME="${MCP_TUNNEL_NAME:-reclaw-mcp}"
HOSTNAME="${MCP_TUNNEL_HOSTNAME:-}"  # e.g. mcp.yourdomain.com — required for DNS route
LOCAL_URL="${MCP_LOCAL_URL:-http://127.0.0.1:8100}"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "Install cloudflared first" >&2
  exit 1
fi

if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
  echo "No ~/.cloudflared/cert.pem — run: cloudflared tunnel login" >&2
  echo "Then re-run this script." >&2
  exit 2
fi

if [[ -z "$HOSTNAME" ]]; then
  echo "Set MCP_TUNNEL_HOSTNAME=mcp.example.com (DNS you control in Cloudflare)" >&2
  exit 2
fi

echo "[1/5] Create tunnel (idempotent if name exists)…"
if ! cloudflared tunnel list 2>/dev/null | grep -q " $NAME "; then
  cloudflared tunnel create "$NAME"
else
  echo "  tunnel $NAME already exists"
fi

TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$NAME" '$2==n {print $1; exit}')"
if [[ -z "$TUNNEL_ID" ]]; then
  echo "Could not resolve tunnel id for $NAME" >&2
  exit 1
fi
echo "  id=$TUNNEL_ID"

CREDS="$HOME/.cloudflared/${TUNNEL_ID}.json"
CFG="$ROOT/data/cloudflared-mcp-config.yml"
mkdir -p "$ROOT/data"

cat >"$CFG" <<YAML
# Generated by scripts/setup-named-mcp-tunnel.sh — do not commit secrets
tunnel: $TUNNEL_ID
credentials-file: $CREDS
ingress:
  - hostname: $HOSTNAME
    service: $LOCAL_URL
  - service: http_status:404
YAML
echo "[2/5] Wrote $CFG"

echo "[3/5] DNS route…"
cloudflared tunnel route dns "$NAME" "$HOSTNAME" || true

PUBLIC="https://${HOSTNAME}/mcp"
echo "$PUBLIC" >"$ROOT/data/mcp_public_url.txt"
echo "$HOSTNAME" >"$ROOT/data/mcp_tunnel_host.txt"
echo "[4/5] Wrote data/mcp_public_url.txt → $PUBLIC"

UNIT=/etc/systemd/system/reclaw-mcp-tunnel.service
echo "[5/5] Install systemd unit (named tunnel)…"
cat >"$UNIT" <<EOF
[Unit]
Description=ReClaw MCP named Cloudflare tunnel
After=network-online.target reclaw-mcp-bridge.service
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/cloudflared tunnel --config $CFG run $TUNNEL_ID
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable reclaw-mcp-tunnel
systemctl restart reclaw-mcp-tunnel
systemctl restart reclaw-mcp-bridge || true
sleep 2
echo "Active: $(systemctl is-active reclaw-mcp-tunnel)"
echo "Public MCP URL: $PUBLIC"
echo "Optional: put Cloudflare Access in front of https://$HOSTNAME (see docs/operator/NAMED-MCP-TUNNEL.md)"
