"""Run every audit test over the ledger and produce the working papers.

Outputs:
    reports/findings.md            audit-style findings summary
    reports/flagged_entries.csv    every flagged entry with the test that caught it
    reports/figures/*.png          Benford chart, posting-hour profile, exceptions by test

Usage:
    python src/run_audit.py        # generates data/ on first run
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

import audit_tests as at
import generate_ledger

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data"
REPORT_DIR = REPO_ROOT / "reports"
FIG_DIR = REPORT_DIR / "figures"

plt.rcParams.update(
    {
        "figure.dpi": 150,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "font.size": 9,
    }
)


def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    if not (DATA_DIR / "journal_entries.csv").exists():
        generate_ledger.main()
    ledger = pd.read_csv(DATA_DIR / "journal_entries.csv", parse_dates=["posting_ts"])
    users = pd.read_csv(DATA_DIR / "users.csv")
    return ledger, users


def main() -> None:
    ledger, users = load_data()
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    findings = {
        "Duplicate payments": at.find_duplicate_payments(ledger),
        "Threshold splitting": at.find_threshold_splitting(ledger),
        "Off-hours postings": at.find_off_hours_postings(ledger),
        "SoD violations": at.find_sod_violations(ledger, users),
        "Round amounts": at.find_round_amounts(ledger),
    }
    benford = at.benford_first_digit(ledger)
    benford_vendors = at.benford_by_vendor(ledger)
    worst_vendor = benford_vendors.iloc[0]

    # --- flagged entries CSV --------------------------------------------------
    flagged = pd.concat(
        [df.assign(audit_test=name) for name, df in findings.items()],
        ignore_index=True,
    )[["audit_test", "entry_id", "posting_ts", "vendor_id", "vendor_name",
       "amount_rm", "posted_by", "approved_by"]]
    flagged.to_csv(REPORT_DIR / "flagged_entries.csv", index=False)

    # --- figures ----------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 4))
    x = list(range(1, 10))
    ax.bar([i - 0.2 for i in x], benford["observed"], width=0.4, label="observed", color="#0f62fe")
    ax.bar([i + 0.2 for i in x], benford["expected"], width=0.4, label="Benford expected", color="#c1c7cd")
    ax.set_xticks(x)
    ax.set_xlabel("First digit")
    ax.set_title(
        f"First-digit analysis, full population "
        f"(MAD {benford['mad']:.4f} = {benford['verdict']})"
    )
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG_DIR / "benford_population.png")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4))
    sub = ledger[ledger.vendor_id == worst_vendor.vendor_id]
    obs = at.benford_first_digit(sub)["observed"]
    ax.bar([i - 0.2 for i in x], obs, width=0.4, label=f"{worst_vendor.vendor_name}", color="#da1e28")
    ax.bar([i + 0.2 for i in x], benford["expected"], width=0.4, label="Benford expected", color="#c1c7cd")
    ax.set_xticks(x)
    ax.set_xlabel("First digit")
    ax.set_title(
        f"Most deviant vendor: {worst_vendor.vendor_name} "
        f"(MAD {worst_vendor['mad']:.4f}, n={worst_vendor.n_entries})"
    )
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG_DIR / "benford_worst_vendor.png")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4))
    human = ledger[ledger.posted_by != "BATCH"]
    ax.hist(human["posting_ts"].dt.hour, bins=range(25), color="#0f62fe",
            edgecolor="white", log=True)
    ax.axvspan(0, 6, color="#da1e28", alpha=0.12, label="night window")
    ax.axvspan(22, 24, color="#da1e28", alpha=0.12)
    ax.set_xlabel("Posting hour")
    ax.set_ylabel("Entries (log scale)")
    ax.set_title("Posting-time profile, human users — night postings visible on log scale")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG_DIR / "posting_hours.png")
    plt.close(fig)

    # --- findings.md ---------------------------------------------------------------
    lines = [
        "# Journal-entry testing — findings summary",
        "",
        f"_Auto-generated by `src/run_audit.py` on {date.today()}. "
        f"Population: **{len(ledger):,} journal lines**, FY2025, {ledger.vendor_id.nunique()} vendors, "
        f"{len(users)} users._",
        "",
        "## Exceptions by test",
        "",
        "| Audit test | Entries flagged | Value flagged (RM) |",
        "|---|---:|---:|",
    ]
    for name, df in findings.items():
        lines.append(f"| {name} | {len(df):,} | {df.amount_rm.sum():,.0f} |")
    lines += [
        "",
        "## Benford's-law analysis",
        "",
        f"- Population of {benford['n']:,} amounts: MAD **{benford['mad']:.4f}** "
        f"({benford['verdict']}); chi-square {benford['chi_square']:,.0f} "
        "(with n this large, chi-square rejects trivial deviations — MAD is the decision metric).",
        f"- Per-vendor drill-down (vendors with ≥100 entries): most deviant is "
        f"**{worst_vendor.vendor_name}** with MAD **{worst_vendor['mad']:.4f}** "
        f"({worst_vendor.verdict}) across {worst_vendor.n_entries} entries — "
        "first digits cluster in 7–9, the classic signature of fabricated amounts "
        "kept below a review limit.",
        "",
        "| Most deviant vendors | MAD | Verdict |",
        "|---|---:|---|",
    ]
    for _, r in benford_vendors.head(5).iterrows():
        lines.append(f"| {r.vendor_name} ({r.n_entries} entries) | {r['mad']:.4f} | {r.verdict} |")
    lines += [
        "",
        "## Charts",
        "",
        "![Benford population](figures/benford_population.png)",
        "![Benford worst vendor](figures/benford_worst_vendor.png)",
        "![Posting hours](figures/posting_hours.png)",
        "",
        "## Basis of testing",
        "",
        "Procedures mirror standard journal-entry testing for fraud risk (ISA 240):",
        "digit-frequency analysis, duplicate-payment search, approval-threshold",
        "splitting, off-hours posting review, segregation-of-duties testing, and",
        "round-amount analysis. Detection logic: [`src/audit_tests.py`](../src/audit_tests.py).",
    ]
    (REPORT_DIR / "findings.md").write_text("\n".join(lines))

    print(f"[audit] {len(flagged):,} entries flagged across {len(findings)} tests")
    print(f"[audit] wrote reports/findings.md, reports/flagged_entries.csv, {len(list(FIG_DIR.glob('*.png')))} figures")


if __name__ == "__main__":
    main()
