"""
Obsidian vault bridge — source of truth on Hetzner (/root/obsidian_vault).

The cyanheads obsidian-mcp-server needs Obsidian desktop + Local REST API.
On the server we connect via filesystem + reclaw-platform MCP vault tools.
This module is the pipeline-side API for durable vault writes.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from core.config import get_settings
from core.handoff import AnalysisPackage, ContentPackage, ResearchPackage

VAULT_ROOT = Path("/root/obsidian_vault")
RURAL_DATA = "Rural Data"
AUDIT_INDEX = "Rural Data/County Audit Index.md"
RAVENSTACK = "Ravenstack"


def vault_path(*parts: str) -> Path:
    """Resolve path under production vault root."""
    settings = get_settings()
    root = settings.obsidian_vault_path
    if not root.is_absolute() or str(root) == "outputs/obsidian":
        root = VAULT_ROOT
    return root.joinpath(*parts)


def write_audit_supplement(
    county: str,
    *,
    research: ResearchPackage | None = None,
    analysis: AnalysisPackage | None = None,
    extra_flags: list[dict] | None = None,
) -> Path:
    """
    Write a county audit supplement note (red flags by category + sources).
    Links from main ContentPackage note.
    """
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    slug = county.lower().replace(" ", "-")
    path = vault_path(RURAL_DATA, f"{date}-{slug}-audit-flags.md")

    lines = [
        "---",
        f"county: {county}",
        f"date: {date}",
        "tags: [county-audit, red-flags, faceless-channel]",
        "---",
        f"# {county} County — Audit Flag Supplement",
        "",
    ]

    if analysis:
        lines.append(f"**Risk score:** {analysis.overall_risk_score}/10  ")
        lines.append(f"**Flags:** {len(analysis.red_flags)}  ")
        lines.append("")
        by_cat: dict[str, list] = {}
        for f in analysis.red_flags:
            by_cat.setdefault(f.category, []).append(f)
        for cat, flags in sorted(by_cat.items(), key=lambda x: -len(x[1])):
            lines.append(f"## {cat.replace('_', ' ').title()} ({len(flags)})")
            lines.append("")
            for f in flags[:8]:
                lines.append(f"- **[{f.severity}]** {f.description[:300]}")
                if f.evidence:
                    lines.append(f"  - Evidence: `{str(f.evidence)[:200]}`")
            lines.append("")

    if research and research.sources:
        lines.append("## Sources")
        lines.append("")
        for s in research.sources[:12]:
            url = getattr(s, "url", None) or ""
            note = getattr(s, "note", "") or ""
            lines.append(f"- {note}" + (f" — {url}" if url else ""))
        lines.append("")

    if extra_flags:
        lines.append("## Discovery Layer")
        lines.append("")
        for item in extra_flags[:10]:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by ReClaw obsidian_bridge. Human review before publish.*")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def update_county_index(county: str, *, note_link: str, flag_count: int, risk: float) -> Path:
    """Maintain County Audit Index MOC in vault."""
    index_path = vault_path(AUDIT_INDEX)
    index_path.parent.mkdir(parents=True, exist_ok=True)

    if index_path.exists():
        body = index_path.read_text(encoding="utf-8")
    else:
        body = """---
tags: [moc, county-audit, indiana]
---

# Indiana County Audit Index

| County | Date | Flags | Risk | Package |
|--------|------|-------|------|---------|
"""

    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    row = f"| {county} | {date} | {flag_count} | {risk:.1f} | [[{note_link}]] |"
    # Replace existing row for same county+date or append
    if f"| {county} |" in body:
        import re

        body = re.sub(rf"\| {re.escape(county)} \|[^\n]+\n", row + "\n", body, count=1)
    else:
        if "|--------|" in body:
            body = body.replace(
                "|--------|------|-------|------|---------|",
                "|--------|------|-------|------|---------|\n" + row,
                1,
            )
        else:
            body += row + "\n"

    index_path.write_text(body, encoding="utf-8")
    return index_path


def publish_package_to_vault(pkg: ContentPackage) -> dict:
    """Write ContentPackage + audit supplement + index update."""
    from core.obsidian_writer import ObsidianWriter

    writer = ObsidianWriter()
    md_path = writer.write_package(pkg)
    supplement = write_audit_supplement(
        pkg.county,
        research=pkg.research,
        analysis=pkg.analysis,
    )
    index = update_county_index(
        pkg.county,
        note_link=md_path.name,
        flag_count=len(pkg.analysis.red_flags),
        risk=pkg.analysis.overall_risk_score,
    )
    return {
        "package_md": str(md_path),
        "audit_supplement": str(supplement),
        "county_index": str(index),
        "vault_root": str(vault_path()),
    }


def vault_health() -> dict:
    """Quick vault connectivity check."""
    root = vault_path()
    rural = vault_path(RURAL_DATA)
    return {
        "vault_root": str(root),
        "exists": root.exists(),
        "rural_data": str(rural),
        "rural_data_exists": rural.exists(),
        "note_count": len(list(rural.glob("*.md"))) if rural.exists() else 0,
        "git_repo": (root / ".git").exists(),
    }